# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: example

builds:
  - id: wheel
    builder: poetry
    buildmode: wheel
  - id: sdist
    builder: poetry
    buildmode: sdist

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

# SBOMs for the archives.
sboms:
  - artifacts: archive

# Sign binaries with cosign.
signs:
  - cmd: cosign
    certificate: "${artifact}.pem"
    output: true
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum

# Create Docker images.
# We create a manifest below, so here the images need the suffix with the
# architecture.
dockers_v2:
  - images:
      - "ghcr.io/goreleaser/example-poetry"
    tags:
      - "{{.Tag}}"
    dockerfile: Dockerfile
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"

# Sign the Docker images with cosign as well.
docker_signs:
  - cmd: cosign
    artifacts: manifests
    output: true
    args:
      - "sign"
      - "${artifact}"
      - "--yes"
